package com.pojo;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
//The class includes a default constructor generated by Lombok's @NoArgsConstructor.
@NoArgsConstructor
//Lombok's @Data annotation generates getter and setter methods for all class properties.
@Data
public class Author {

	// The @Id annotation indicates that 'id' is the primary key for this entity.
	// The @GeneratedValue annotation specifies the strategy for generating unique
	// IDs.
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;

	private String authorName;

	// The @Temporal annotation specifies that 'dateOfBirth' is a temporal field, meaning it stores date and time information.
	@Temporal(TemporalType.TIMESTAMP)
	private Date dateOfBirth;

	private String nationality;

	private String gender;

	// Getters and setters for the class properties.
	public Integer getId() {
		return id;
	}

	public String getAuthorName() {
		return authorName;
	}

	public Date getDateOfBirth() {
		return dateOfBirth;
	}

	public String getNationality() {
		return nationality;
	}

	public String getGender() {
		return gender;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public void setAuthorName(String authorName) {
		this.authorName = authorName;
	}

	public void setDateOfBirth(Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	public void setNationality(String nationality) {
		this.nationality = nationality;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

}
